- hosts: all
  tasks:
    - name: stop container
      shell:  docker container stop webapp-container                    #name of container 
    - name: remove container
      shell: docker container rm webapp-container
    - name: remove docker image
      shell: docker image rm trainingskumar/webproject1                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name webapp-container -p 9000:80 trainingskumar/webproject1     #(docker-job>> name of jenkins job)
